import { catalogue, inventory } from "./catalogue.js";

// PACK-01: single source for generated release records. The committed
// skills/vectra-axi/SKILL.md command table and docs/coverage.md are
// projections of the executable catalogue and the capability inventory, so
// help, skill and coverage cannot drift apart. scripts/generate-docs.mjs
// writes both files; test/generated.test.ts fails when they are stale.

// One row per executable leaf in catalogue order, matching the home-view
// help. Every leaf is implemented by a vectra-axi handler (native).
// Local views stay offline; QUX and RUX reads use the read-only session, tag
// replaces, bulk tag changes, note appends and assignment sets use the gated
// WRITE-00 coordinator.
export function skillCommandTable(): string {
  return [
    "| Command | Capability | Vectra effect |",
    "|---|---|---|",
    ...Object.keys(catalogue).map((leaf) => {
      const effect = inventory.operations.find((operation) => operation.command === leaf)?.effect ?? "read";
      return `| \`vectra-axi ${leaf}\` | native | ${effect} |`;
    }),
  ].join("\n");
}

const DISPOSITIONS = ["named", "reviewed-raw", "planned", "blocked", "unavailable", "deprecated", "unreviewed"] as const;

export function coverageDocument(): string {
  const operations = inventory.operations;
  const count = (disposition: string): number =>
    operations.filter((operation) => operation.disposition === disposition).length;
  const rows = operations.map((operation) =>
    `| \`${operation.id}\` | ${operation.command ?? "-"} | ${operation.slice} | ${operation.deployment} ${operation.apiVersion} | ${operation.paging} | ${operation.disposition} |`);
  const families = inventory.deferredFamilies.map((family) =>
    `- \`${family.id}\` (${family.deployment} ${family.apiVersion}, ${family.disposition}): ${family.rationale}`);
  return [
    "<!-- Generated by scripts/generate-docs.mjs from inventory/capabilities.json. Do not hand-edit. -->",
    "",
    "# vectra-axi coverage",
    "",
    "This is the supported QUX and RUX SOC read surface with gated QUX single and bulk tag-write, note-write and assignment-write families, not full Vectra API coverage.",
    "Only `named` operations have an implemented, tested command leaf; every other",
    "operation remains planned, blocked or unreviewed until its own slice ships.",
    "",
    "## Counts",
    "",
    ...DISPOSITIONS.map((disposition) => `- ${disposition}: ${count(disposition)}`),
    "",
    "## Operations",
    "",
    "| Operation | Command | Slice | Deployment/API | Paging | Disposition |",
    "|---|---|---|---|---|---|",
    ...rows,
    "",
    "## Deferred families",
    "",
    ...families,
    "",
  ].join("\n");
}
